/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        dark: {
          bg: 'rgb(var(--bg-page-rgb) / <alpha-value>)',
          surface: 'rgb(var(--bg-surface-rgb) / <alpha-value>)',
          card: 'rgb(var(--bg-card-rgb) / <alpha-value>)',
          cardHover: 'rgb(var(--bg-card-hover-rgb) / <alpha-value>)',
          border: 'rgb(var(--border-color-rgb) / <alpha-value>)',
          subtle: 'rgb(var(--bg-subtle-rgb) / <alpha-value>)',
        },
        brand: {
          navy: 'rgb(var(--bg-sidebar-rgb) / <alpha-value>)',
          navyDark: 'rgb(var(--bg-sidebar-active-rgb) / <alpha-value>)',
          primary: 'rgb(var(--color-primary-rgb) / <alpha-value>)',
          primaryHover: 'rgb(var(--color-primary-hover-rgb) / <alpha-value>)',
          primaryLight: 'rgb(var(--color-primary-light-rgb) / <alpha-value>)',
          accent: 'rgb(var(--color-accent-rgb) / <alpha-value>)',
          cyan: '#06B6D4',
          fire: 'var(--reaction-fire)',
          orange: 'rgb(var(--color-primary-rgb) / <alpha-value>)',
          orangeHover: 'rgb(var(--color-primary-hover-rgb) / <alpha-value>)',
          orangeLight: 'rgb(var(--color-primary-light-rgb) / <alpha-value>)',
          purple: 'rgb(var(--color-primary-rgb) / <alpha-value>)',
        },
        sidebar: {
          DEFAULT: 'rgb(var(--bg-sidebar-rgb) / <alpha-value>)',
          hover: 'rgb(var(--bg-sidebar-hover-rgb) / <alpha-value>)',
          active: 'rgb(var(--bg-sidebar-active-rgb) / <alpha-value>)',
          text: 'var(--text-sidebar)',
          muted: 'var(--text-sidebar-muted)',
          border: 'var(--border-sidebar)',
        },
        slate: {
          50: 'rgb(var(--bg-subtle-rgb) / <alpha-value>)',
          100: 'rgb(var(--text-main-rgb) / <alpha-value>)',
          200: 'rgb(var(--text-main-rgb) / <alpha-value>)',
          300: 'rgb(var(--text-secondary-rgb) / <alpha-value>)',
          400: 'rgb(var(--text-muted-rgb) / <alpha-value>)',
          500: 'rgb(var(--text-placeholder-rgb) / <alpha-value>)',
          600: 'rgb(var(--text-secondary-rgb) / <alpha-value>)',
          700: 'rgb(var(--text-secondary-rgb) / <alpha-value>)',
          800: 'rgb(var(--text-secondary-rgb) / <alpha-value>)',
          900: 'rgb(var(--text-main-rgb) / <alpha-value>)',
          950: 'rgb(var(--text-main-rgb) / <alpha-value>)',
        },
        sky: {
          50: 'rgb(var(--color-primary-light-rgb) / <alpha-value>)',
          100: '#E0E3FD',
          200: '#C7CDFC',
          300: '#A5B0FA',
          400: 'rgb(var(--color-primary-rgb) / <alpha-value>)',
          500: 'rgb(var(--color-primary-rgb) / <alpha-value>)',
          600: 'rgb(var(--color-primary-rgb) / <alpha-value>)',
          700: 'rgb(var(--color-primary-hover-rgb) / <alpha-value>)',
          800: 'rgb(var(--color-primary-active-rgb) / <alpha-value>)',
          900: '#2A1C91',
          950: '#180E5E',
        },
        reaction: {
          laugh: 'var(--reaction-laugh)',
          skull: 'var(--reaction-skull)',
          cry: 'var(--reaction-cry)',
          fire: 'var(--reaction-fire)',
        },
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        display: ['"Outfit"', '"Plus Jakarta Sans"', 'sans-serif'],
      },
      boxShadow: {
        none: 'none',
        sm: 'none',
        DEFAULT: 'none',
        md: 'none',
        lg: 'none',
        xl: 'none',
        '2xl': 'none',
        inner: 'none',
        'glow-primary': 'none',
        'glow-navy': 'none',
        'glow-orange': 'none',
        card: 'none',
        sheet: 'none',
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      keyframes: {
        bounceSubtle: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.12)' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.85' },
        },
      },
      animation: {
        'bounce-subtle': 'bounceSubtle 0.25s ease-in-out',
        'pulse-glow': 'pulseGlow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
}
